name: Mobile APK Compilation Pipeline
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Setup Flutter SDK Environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Flet Compiler Platform
        run: |
          pip install --upgrade pip
          pip install flet
          
      - name: Native Package Building Campaign
        run: |
          flet build apk --project-name grimauto --org org.icedcoffeemilktea
          
      - name: Upload Finished APK Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GrimAutoPackage
          path: build/apk/*.apk
